server:
  port: 8082
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.example.store.entity


